---
version: '3.5'
services:
  wetty:
    image: wettyoss/wetty
    build:
      context: .
      dockerfile: containers/wetty/Dockerfile
    entrypoint: yarn docker-compose-entrypoint
    tty: true
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    volumes:
      - ./conf:/usr/src/app/conf
      - ./containers:/usr/src/app/containers
      # - ./src:/usr/src/app/src-backup
      - ./src:/usr/src/app/src
    environment:
      SSHHOST: '192.168.1.3'
      SSHPORT: 22
      NODE_ENV: 'development'

  web:
    # image: nginx
    image: openresty/openresty:centos
    # image: openresty/openresty:1.21.4.1-3-alpine-fat
    volumes:
      - ./conf/nginx.template:/etc/nginx/conf.d/wetty.template
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/redis-conf.lua:/etc/nginx/conf.d/redis-conf.lua
    ports:
      - '80:80'
    environment:
      - NGINX_DOMAIN=localhost
      - NGINX_PORT=80
      - WETTY_HOST=wetty
      - WETTY_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >-
      /bin/bash -c "envsubst \
      '$${NGINX_DOMAIN},$${NGINX_PORT},$${WETTY_HOST},$${WETTY_PORT},$${REDIS_HOST},$${REDIS_PORT}' < \
      /etc/nginx/conf.d/wetty.template > /etc/nginx/conf.d/default.conf && nginx \
      -g 'daemon off;' -c /etc/nginx/nginx.conf"

  wetty-ssh:
    build:
      context: .
      dockerfile: containers/ssh/Dockerfile
    image: wettyoss/wetty:ssh

  # https://github.com/bitnami/containers/blob/main/bitnami/redis/docker-compose.yml
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data

networks:
  default:
    name: wetty

volumes:
  redis_data:
    driver: local
