---
version: '3.5'
services:
  wetty:
    image: wettyoss/wetty
    build:
      context: .
      dockerfile: containers/wetty/Dockerfile
    entrypoint: yarn docker-compose-entrypoint
    tty: true
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    volumes:
      - ./conf:/usr/src/app/conf
      - ./containers:/usr/src/app/containers
      - ./src:/usr/src/app/src
    environment:
      SSHHOST: '192.168.1.3'
      SSHPORT: 22
      NODE_ENV: 'development'

  web:
    image: nginx
    volumes:
      - ./conf/nginx.template:/etc/nginx/conf.d/wetty.template
    ports:
      - '80:80'
    environment:
      - NGINX_DOMAIN=localhost
      - NGINX_PORT=80
      - WETTY_HOST=wetty
      - WETTY_PORT=3000
    command: >-
      /bin/bash -c "envsubst
      '$${NGINX_DOMAIN},$${NGINX_PORT},$${WETTY_HOST},$${WETTY_PORT}' <
      /etc/nginx/conf.d/wetty.template > /etc/nginx/conf.d/default.conf && nginx
      -g 'daemon off;'"

  wetty-ssh:
    build:
      context: .
      dockerfile: containers/ssh/Dockerfile
    image: wettyoss/wetty:ssh

networks:
  default:
    name: wetty
